### ISSUE TITLE
Release Iteration 1

### ISSUE THREAD

**Issue by craftpaperbag** [born-in-makuhari/emaki#26]
Iteration1のリリース準備。

DockerFileを作りたい。

### tasks

とりあえずDockerFileの基礎をつくります。
基本はこれで
https://hub.docker.com/_/ruby/

- [ ] dockerで起動させる
- :alarm_clock: redisを別立て
- :alarm_clock: ファイル保存用ディレクトリを外出し

**Comment by craftpaperbag** [comment]
ちょっと

**Comment by craftpaperbag** [comment]
- PDFを投稿しても０ページと認識されてしまう
    - OSXにて　ghostscriptが入っていない時と同じ動作
- 日本語でユーザー名・スライド名を入力すると500エラー
    - 以下のエラー
```
http://localhost:8080/new -> /slides
2015-08-29 09:45:05 - ArgumentError - invalid byte sequence in US-ASCII:
	/usr/local/bundle/gems/temple-0.7.6/lib/temple/utils.rb:47:in `gsub'
	/usr/local/bundle/gems/temple-0.7.6/lib/temple/utils.rb:47:in `escape_html'
	/srv/emaki/views/slide.slim:22:in `block in singleton class'
	/srv/emaki/views/slide.slim:-2:in `instance_eval'
	/srv/emaki/views/slide.slim:-2:in `singleton class'
	/srv/emaki/views/slide.slim:-4:in `__tilt_70246037355260'
	/usr/local/bundle/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
	/usr/local/bundle/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
	/usr/local/bundle/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:743:in `slim'
	emaki.rb:140:in `block in <main>'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/usr/local/bundle/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/usr/local/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/usr/local/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/usr/local/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```
